qqr = input('Digite algo ')
print('O tipo primitivo desse valor é:', type(qqr))
print('Só tem espaços?', qqr.isspace())
print('É um número?', qqr.isnumeric())
print('É alfabético?', qqr.isalpha())
print('É alfanumérico? {}'.format(qqr.isalnum()))
print('Esta em maiúsculas? {}'.format(qqr.isupper()))
print('Está em minúsculas? {}'.format(qqr.islower()))
print('Está capitalizada? {}'.format(qqr.istitle()))
